jobs:
  build:
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Update this line to a supported version
- name: Install dependencies
  run: pip install -r requirements.txt
